// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7CnNZarWIliaPfOrEQMCGC4fTYMw6l_c',
    appId: '1:356696843049:web:98f5b9993add94ce5a0d38',
    messagingSenderId: '356696843049',
    projectId: 'scholar-chat-app-12961',
    authDomain: 'scholar-chat-app-12961.firebaseapp.com',
    storageBucket: 'scholar-chat-app-12961.appspot.com',
    measurementId: 'G-1PS34FQXG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC5a--F9RMiQwp8cvniM6QoT9F69HAp3k',
    appId: '1:356696843049:android:043e4e7e176937c85a0d38',
    messagingSenderId: '356696843049',
    projectId: 'scholar-chat-app-12961',
    storageBucket: 'scholar-chat-app-12961.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN6OqBQQXgIwVb8xGieMPUeIZdFBbtL-k',
    appId: '1:356696843049:ios:379805bdb99dcc355a0d38',
    messagingSenderId: '356696843049',
    projectId: 'scholar-chat-app-12961',
    storageBucket: 'scholar-chat-app-12961.appspot.com',
    iosClientId: '356696843049-u13lbr2gncfsg8hde4e8980rts08p43t.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN6OqBQQXgIwVb8xGieMPUeIZdFBbtL-k',
    appId: '1:356696843049:ios:6d586e9b274b8e9b5a0d38',
    messagingSenderId: '356696843049',
    projectId: 'scholar-chat-app-12961',
    storageBucket: 'scholar-chat-app-12961.appspot.com',
    iosClientId: '356696843049-6i5ga834fqge52oo2psucs0v4v07rh4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarApp.RunnerTests',
  );
}
